// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz611WC-I7f3bDG68UzsZM2dvnkU5gXzg',
    appId: '1:956268765900:web:d38c0e49e85719ca05d869',
    messagingSenderId: '956268765900',
    projectId: 'smart-campus-4f4bd',
    authDomain: 'smart-campus-4f4bd.firebaseapp.com',
    storageBucket: 'smart-campus-4f4bd.firebasestorage.app',
    measurementId: 'G-HHJZQRB201',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqf_G3715o7XgYeg6Wqz3ZF_jYebKSJc',
    appId: '1:956268765900:android:c5f0d5f93a6080de05d869',
    messagingSenderId: '956268765900',
    projectId: 'smart-campus-4f4bd',
    storageBucket: 'smart-campus-4f4bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxpG8kRGtJzlXUEQBKf5u-SQVAdE1d-qQ',
    appId: '1:956268765900:ios:e3eb2daaa8f68f3d05d869',
    messagingSenderId: '956268765900',
    projectId: 'smart-campus-4f4bd',
    storageBucket: 'smart-campus-4f4bd.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxpG8kRGtJzlXUEQBKf5u-SQVAdE1d-qQ',
    appId: '1:956268765900:ios:e3eb2daaa8f68f3d05d869',
    messagingSenderId: '956268765900',
    projectId: 'smart-campus-4f4bd',
    storageBucket: 'smart-campus-4f4bd.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz611WC-I7f3bDG68UzsZM2dvnkU5gXzg',
    appId: '1:956268765900:web:2fa69196824a1cdf05d869',
    messagingSenderId: '956268765900',
    projectId: 'smart-campus-4f4bd',
    authDomain: 'smart-campus-4f4bd.firebaseapp.com',
    storageBucket: 'smart-campus-4f4bd.firebasestorage.app',
    measurementId: 'G-MM82DX3N3N',
  );
}
